//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialysisPrescription
    {
        public long Id { get; set; }
        public int PrescriptionTypeId { get; set; }
        public bool Haemodialysis { get; set; }
        public bool Haemodialfiltration { get; set; }
        public int DialyserLevelIds { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> UnfractionatedHeparin { get; set; }
        public Nullable<decimal> LowMolecularWeightHeparin { get; set; }
        public string Other { get; set; }
        public Nullable<long> DialysisAccessOptionId { get; set; }
        public string NeedleSize { get; set; }
        public Nullable<decimal> PumpSpeed { get; set; }
        public string AcidConcentrate { get; set; }
        public Nullable<decimal> DialysateFlow { get; set; }
        public Nullable<decimal> DialysateTemparature { get; set; }
        public Nullable<decimal> GoalKtv { get; set; }
        public Nullable<decimal> DryWeight { get; set; }
        public Nullable<decimal> Ultrafiltration { get; set; }
        public Nullable<int> RepeatScript { get; set; }
        public Nullable<bool> Sodium { get; set; }
        public Nullable<bool> UFProfile { get; set; }
        public Nullable<bool> More { get; set; }
        public string MoreText { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Finalised { get; set; }
        public Nullable<long> DocumentId { get; set; }
        public string DocumentKey { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual PrescriptionType PrescriptionType { get; set; }
    }
}
