//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.NURSEs = new HashSet<NURSE>();
        }
    
        public int DOC_ID { get; set; }
        public string DNAME { get; set; }
        public string GENDER { get; set; }
        public string QUALIFICATION { get; set; }
        public string JOB_SPECIFICATION { get; set; }
        public string HOSP_NAME { get; set; }
    
        public virtual HOSPITAL HOSPITAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NURSE> NURSEs { get; set; }
    }
}
