//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicClaim
    {
        public int claim_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> provider_id { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public Nullable<decimal> claim_amount { get; set; }
        public string diagnosis_code { get; set; }
        public string procedure_code { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> submitted_date { get; set; }
        public Nullable<System.DateTime> adjudicated_date { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    }
}
