//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.Infrastructure.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISHmockEntities : DbContext
    {
        public ISHmockEntities()
            : base("name=ISHmockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIAGNOSI> DIAGNOSIS { get; set; }
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<EXAMINE> EXAMINEs { get; set; }
        public virtual DbSet<HOSPITAL> HOSPITALs { get; set; }
        public virtual DbSet<MEDICINE> MEDICINEs { get; set; }
        public virtual DbSet<MEDICINE_COUNTRY> MEDICINE_COUNTRY { get; set; }
        public virtual DbSet<NURSE> NURSEs { get; set; }
        public virtual DbSet<PATIENT> PATIENTs { get; set; }
        public virtual DbSet<PURCHASE> PURCHASEs { get; set; }
        public virtual DbSet<RECEPTION> RECEPTIONs { get; set; }
        public virtual DbSet<VISIT> VISITs { get; set; }
    }
}
