//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE_COUNTRY
    {
        public int REG_NO { get; set; }
        public string MAN_COUNTRY { get; set; }
    
        public virtual MEDICINE MEDICINE { get; set; }
    }
}
