//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NURSE()
        {
            this.DIAGNOSIS = new HashSet<DIAGNOSI>();
        }
    
        public int id { get; set; }
        public string NAME { get; set; }
        public string GENDER { get; set; }
        public int DOC_ID { get; set; }
        public string HOSP_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAGNOSI> DIAGNOSIS { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
    }
}
