//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialization
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PrescriptionTypeId { get; set; }
    
        public virtual PrescriptionType PrescriptionType { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
    }
}
